
services:
  mariadb:
    build : ./requirements/mariadb
    image: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: mariadb
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image : wordpress
    volumes:
      - Wordpress:/var/www/html/
    networks:
      - inception
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_EMAIL=${MYSQL_EMAIL}

      - WORDPRESS_HOST=${WORDPRESS_HOST}

      - SEC_USER_USER=${SEC_USER_USER}
      - SEC_USER_PASS=${SEC_USER_PASS}
      - SEC_USER_ROLE=${SEC_USER_ROLE}
      - SEC_USER_MAIL=${SEC_USER_MAIL}
    depends_on:
      - mariadb
    restart: always

  nginx:
    build: ./requirements/nginx
    image : nginx
    container_name: nginx

    networks:
      - inception
    volumes:
      - ./requirements/nginx/tools/nginx.conf:/etc/nginx/nginx.conf
      - Wordpress:/var/www/html/
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: always


networks:
  inception:


volumes:
  Wordpress:
    driver: local
    driver_opts:
      type: none # which filesystem is to be used
      o: bind # we specify the access of the container and the host machine to this folder we can change it to read-only or read write
      device: /home/eboulhou/data/Wordpress
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eboulhou/data/DB