
version: '3'
services:
  mariadb:
    build: 
      context: ./requirements/mariadb
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_ROOT: ${MYSQL_ROOT_PASSWORD}
    container_name: mariadb
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inception
    # ports:
    # - "3306:3306"
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - Wordpress:/var/www/html
    networks:
      - inception
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_EMAIL=${MYSQL_EMAIL}
      - WORDPRESS_HOST=${WORDPRESS_HOST}

      - SEC_USER_USER=${SEC_USER_USER}
      - SEC_USER_PASS=${SEC_USER_PASS}
      - SEC_USER_ROLE=${SEC_USER_ROLE}
      - SEC_USER_MAIL=${SEC_USER_MAIL}
    depends_on:
      - mariadb
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - inception
    volumes:
      - ./requirements/nginx/tools/nginx.conf:/etc/nginx/nginx.conf
      - Wordpress:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: always


networks:
  inception:


volumes:
  Wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mehdi/data/Wordpress
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mehdi/data/DB